### PR TITLE
adds new game sound with animation

### PR DESCRIPTION
**Pull request by abhisheksharm-3**
Hey @idna001 , please check the implementation!
closes issue #58

### CODE REVIEW

**Review by idna001 — APPROVED** [review]
Nice Animation and sound you added, thank you!
Can you please add the source of the sound in README, before I merge it

**Comment by abhisheksharm-3** [comment]
the sound is from Pixabay, which is already mentioned in Readme, should i add specific link to this sound in credits section

**Comment by idna001** [comment]
@abhisheksharm-3 Ah perfect that's fine, If you want you can comment the link here in the PR. 
Thanks for your contribution, enjoy Hacktoberfest

**Comment by abhisheksharm-3** [comment]
Sure @idna001 [Start Sound](https://pixabay.com/sound-effects/game-start-6104/) - Sound effect for game start
Thanks for the opportunity!

**Pull request merged**
